services:
  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

  mysqldb:
    image: mysql:8.0
    volumes:
      - /etc/mysql/conf.d:/root/docker/test-mysql/conf.d
      - ./db/mysql/mysql:/var/lib/mysql
      - ./db/mysql/init.sql:/docker-entrypoint-initdb.d/1-init.sql
    restart: always
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - 6603:3306
    expose:
      - 3306

  superset:
    build: ./ui/superset
    container_name: superset
    depends_on:
      - redis
      - mysqldb
    entrypoint: /app/superset-entrypoint.sh
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_HOST=mysqldb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://${MYSQL_USER}:${MYSQL_PASSWORD}@mysqldb:${MYSQL_PORT}/${MYSQL_DATABASE}
    ports:
      - 8088:8088
    volumes:
      - superset_home:/app/superset_home
      - ./ui/superset/superset_config.py:/app/superset_config.py
      - ./ui/superset/Dockerfile:/app/Dockerfile
      - ./ui/superset/superset-entrypoint.sh:/app/superset-entrypoint.sh

  redis:
    image: redis:6.2
    container_name: redis
    volumes:
      - redis_data:/data

  mysql-backup:
    image: databack/mysql-backup
    restart: always
    environment:
      DB_USER: $MYSQL_USER
      DB_PASS: $MYSQL_PASSWORD
      DB_SERVER: $MONGO_HOST
      DB_PORT: 3306
      DB_DUMP_FREQ: 1440
      DB_DUMP_DEBUG: "true"
      DB_DUMP_TARGET: ./data/mysql_backup
      COMPRESSION: bzip2
    volumes:
      - ./data/mysql_backup:/db

volumes:
  superset_home:
  redis_data: